name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: wordpress-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 170030262/blog-post-workflow@master
        with:
          feed_list: "https://www.bloglovin.com/blogs/amazingtricks-20596137"
